language: c
sudo: required
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-ocaml.sh
os:
  - linux
  - osx

env:
  - OCAML_VERSION=4.09

script:
  - git submodule update --init --recursive
  - bash -ex .travis-ocaml.sh
  - make install_deps
  - make run
