language: c
sudo: required
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-ocaml.sh
os:
  - linux

env:
  - OCAML_VERSION=4.09

script:
  - git submodule update --init --recursive
  - apt install -y libprocps-dev
  - bash -ex .travis-ocaml.sh
  - opam install dune
  - make install_deps
  - make run
